### ISSUE TITLE
Make sure we are not missing splash screen xml file in `AndroidResource`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.resizetizer#108] opened 2023-03-29 16:35 UTC
I'm not too sure, but we might be missing including `uno_splash_image.xml` in `AndroidResource`

**Comment by Youssef1313** [comment] 2023-03-29 16:38
@pictos Can you please confirm if I'm correct?

**Comment by pictos** [comment] 2023-03-29 19:34
@Youssef1313 it's included at some point because the app can run sometimes, so it's something related to the incremental builds. The fix on Xamarin.Android repo, that you mention in another issue isn't released yet, so maybe we have to wait for it?

**Comment by Youssef1313** [comment] 2023-03-29 19:41
This is not about the build issue (currently Jerome is looking into it), but I found the only place we include an android resource is:

https://github.com/unoplatform/uno.resizetizer/blob/a394b82c2eeae8e3b8ca858b5d5aa979d32c718d/src/.nuspec/Uno.Resizetizer.targets#L544-L546

I think this doesn't include `uno_splash_image.xml`, so was wondering how it is included (if at all), and whether this can cause issues.

cc @jeromelaban as well for thoughts.

**Comment by pictos** [comment] 2023-03-29 19:55
@Youssef1313 the splash screen are handled in another task, here's where the splash assets are generated

https://github.com/unoplatform/uno.resizetizer/blob/a394b82c2eeae8e3b8ca858b5d5aa979d32c718d/src/.nuspec/Uno.Resizetizer.targets#L386-L397

**Comment by Youssef1313** [comment] 2023-03-29 20:04
@pictos Yes I see it's generated here, but not added to `AndroidResource` after generated. So trying to understand why it's not added or if it's added somewhere I can't see.

**Comment by pictos** [comment] 2023-03-29 20:24
@Youssef1313 we added the generated assets as `LibraryResourceDirectories`, that's handled by Xamarin.Android build tasks in the pipeline, you can check that on binlog

**Comment by nickrandolph** [comment] 2023-03-30 05:11
@Youssef1313 is this a derived issue or duplicate of https://github.com/unoplatform/uno.resizetizer/issues/106?

**Comment by Youssef1313** [comment] 2023-03-30 13:57
> @Youssef1313 is this a derived issue or duplicate of #106?

Nope.

**Closed** 2023-03-30 13:56 UTC
