### ISSUE TITLE
[iOS/Android] App icons don't show the correct size it is showing a bit zoomed

### ISSUE THREAD

**Issue by Darsh0307** [unoplatform/uno.resizetizer#102] opened 2023-03-23 23:40 UTC
## Current behavior

The App icon is showing a bit zoomed for the Android as well as IOS  , I will also attach the screenshot of both the platform

**IOS** 

<img width="400" alt="Screenshot 2023-03-24 at 5 01 17 AM" src="https://user-images.githubusercontent.com/90713481/227387048-f31c23e1-7f8e-4160-b90e-2fc146050372.png">

**Android**
<img width="356" alt="Screenshot 2023-03-24 at 5 03 05 AM" src="https://user-images.githubusercontent.com/90713481/227387099-4e875f03-d49c-49cf-b838-f67476b0018c.png">

## Expected behavior

App Icon should have been shown clearly and fit but unfortunately it is not 

## How to reproduce it (as minimally and precisely as possible)

```
<UnoIcon Include="$(MSBuildThisFileDirectory)Icons\iconapp.svg"
				 ForegroundFile="$(MSBuildThisFileDirectory)Icons\appconfig.svg"
				 Color="#FFFFFF" />
```

## Environment

Nuget Package: uno.resizetizer

Package Version(s): 1.0.2

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [x ]  2022 (version: Version 17.5.2)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by nickrandolph** [comment] 2023-04-12 05:31
@Darsh0307 you should be able to add the following to zoom the icon so it works for ios/android
ForegroundScale="0.65"
I'm going to close this issue as it's a duplicate of the wider discussion around app icon handling: https://github.com/unoplatform/uno.resizetizer/issues/109

**Closed by nickrandolph** 2023-04-12 05:31 UTC
Labels: kind/bug, triage/untriaged
