### ISSUE TITLE
Support .svg formats

### ISSUE THREAD

**Issue by limeniye** [unoplatform/uno.resizetizer#256] opened 2024-04-29 12:58 UTC
### Attached discussion: 
https://github.com/unoplatform/uno/discussions/16456

### The problem

In previous version of Uno.Resizetizer I had a good quality pictures via .svg format for WinUI.
After the packages update I had to change the .svg to .png (because the .svg format doesn't work now for me)
When I have changed the formats to .png -- the quality of pictures **were downgraded.**

### What I have tried
I have tried to move the image file to the ```/Svg/``` folder but it didn't display.

![image](https://github.com/unoplatform/uno/assets/69314237/0123abb7-2714-4230-a108-711af72b460d)

### Attached files
[SvgIssue.zip](https://github.com/unoplatform/uno/files/15149466/SvgIssue.zip)

### For which platform

Windows (WinAppSDK)

**Comment by MartinZikmund** [comment] 2024-04-30 06:41
@limeniye transfered here as the issue is caused by Resizetizer

**Comment by limeniye** [comment] 2024-04-30 09:43
Also I have one more question: 
Why I can't use the upper case names for images?

**Comment by pedrojesus-work** [comment] 2024-04-30 18:18
@limeniye, I could use the `.svg` on winUI to show up the svg on both Packaged and Unpackged, as you can see in the image below:

![image](https://github.com/unoplatform/uno.resizetizer/assets/162186634/da836e90-898c-4a3c-854e-8b2205cc516a)

```xml
<Image
	Height="50"
	HorizontalAlignment="Center"
	Source="ms-appx:///UnoApp77/Svg/tikal.svg"
	Stretch="Uniform" />
```

The thing, is that on old templates we've a [instruction on csproj](https://github.com/unoplatform/uno.resizetizer/blob/main/samples/NewTemplate/Resizetizer.Extensions.Sample/Resizetizer.Extensions.Sample.csproj#L53) that make all `svg` inside the assets folder to be UnoImage, and Uno.Resizetizer removes the `.svg` that're marked as UnoImages, in order to avoid it to be added to final app. If you want to use the `svg` without resizing it, create a `Svg` folder, as you did, and select the `.svg` as content.

![image](https://github.com/unoplatform/uno.resizetizer/assets/162186634/a8eebe22-907c-4b5b-8789-23f316883851)

I'll confirm if we've something like that on Uno.Sdk, but I think so.

**Comment by pedrojesus-work** [comment] 2024-04-30 18:20
> Why I can't use the upper case name for image?

@limeniye, we describe the reason on our docs, right [here](https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?tabs=classlib%2CAndroid#usage)

**Comment by pedrojesus-work** [comment] 2024-04-30 21:30
updated sample that works:

[svg_sample.zip](https://github.com/unoplatform/uno.resizetizer/files/15171246/svg_sample.zip)


But I found an issue, right now we just lookup for asset's name inside the `ContentFilesProjectOutputGroupOutput` collectoin, I'll submit a PR that will look for the full path comparing with `UnoImages` collection instead. It will allow devs to have the same `.svg`  name, but in another folder location, that was used for a `UnoImage` packaged inside the app.

**Comment by agneszitte** [comment] 2024-05-02 19:11
From @Youssef1313:
> For Resizetizer, I'm not sure, but here:
> https://github.com/unoplatform/uno.resizetizer/blob/ec018465f3b7dd7286a46597ebc2b9b66776ee7f/src/Resizetizer/src/SkiaSharpTools.cs#L36, we may need to set IsAntialias = true and FilterQuality = SKFilterQuality.High

FYI @pedrojesus-work

**Comment by limeniye** [comment] 2024-05-05 12:09
Thanks. Indeed, a two different images with the same name has a conflict.
Thanks everyone. Your suggestions helped me.
I guess after the **257** pull we can close the issue.

**Comment by limeniye** [comment] 2024-05-05 14:29
@pedrojesus-work, I have the following problem: 

![image](https://github.com/unoplatform/uno.resizetizer/assets/69314237/cd914bd1-c2d3-4c41-8c0f-f4861ba963d6)

As you can see the **.svg** file, inside of **/Svg/** folder is displaying well. 
But the file inside of **/Svg/** ** **/*.svg** -- is not.
Does your PR will fix this problem also?

**Comment by pedrojesus-work** [comment] 2024-05-06 19:06
@limeniye it should be, can you try the latest dev package? Anyway @dansiegel will move this forward

**Comment by limeniye** [comment] 2024-05-06 19:39
@pedrojesus-work, Unfortunately, images inside of subfolders (```ms-appx:///UnoApp77/Assets/Svg/Folder/image.svg```) doesn't display with the Uno.Resizetizer ```1.5.0-dev.58``` for me.

**Comment by dansiegel** [comment] 2024-05-06 20:04
@limeniye when this is merged to Uno this should help as well it seems that on the Uno targets we aren't actually including Svg's as Content even though we do have the exclude for the UnoImage.
unoplatform/uno#16593

**Closed** 2024-05-06 20:06 UTC
Labels: kind/enhancement

**Comment by agneszitte** [comment] 2024-05-09 00:46
> From @Youssef1313:

> > For Resizetizer, I'm not sure, but here:
> > [uno.resizetizer/src/Resizetizer/src/SkiaSharpTools.cs](https://github.com/unoplatform/uno.resizetizer/blob/ec018465f3b7dd7286a46597ebc2b9b66776ee7f/src/Resizetizer/src/SkiaSharpTools.cs#L36)

> https://github.com/unoplatform/uno.resizetizer/blob/ec018465f3b7dd7286a46597ebc2b9b66776ee7f/src/Resizetizer/src/SkiaSharpTools.cs#L36

> ColorFilter = SKColorFilter.CreateBlendMode(tint, SKBlendMode.SrcIn) 
> , we may need to set IsAntialias = true and FilterQuality = SKFilterQuality.High
> fyi @pedrojesus-work, cf. related changes in Uno -> [unoplatform/uno#16558 (files)](https://github.com/unoplatform/uno/pull/16558/files)

@dansiegel I think we should match for Resizetizer [here](https://github.com/unoplatform/uno.resizetizer/blob/ec018465f3b7dd7286a46597ebc2b9b66776ee7f/src/Resizetizer/src/SkiaSharpTools.cs#L36) the [latest changes](https://github.com/unoplatform/uno/pull/16558/files) @Youssef1313 made in the Uno repo to set `IsAntialias = true` and `FilterQuality = SKFilterQuality.High`.
