### ISSUE TITLE
Default uno template contains icon errors

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.resizetizer#288] opened 2024-06-06 16:03 UTC
## Current behavior

A default app template (blank or recommended) will show errors like this one:

![image](https://github.com/unoplatform/uno.resizetizer/assets/5839577/610874ad-60a1-4070-974b-7e77f09fd6c4)

## Expected behavior

No errors.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dansiegel** [comment] 2024-06-11 13:42
I'm unable to reproduce this

**Comment by jeromelaban** [comment] 2024-06-14 12:26
This is caused by the fact that the PWA app manifest being used is the one coming from the Platforms folder. We should likely change the LogicalName of the file (not sure if the bootstrapper supports it).

**Comment by dansiegel** [comment] 2024-06-17 14:39
As discussed with @jeromelaban the fix for this should probably be coming from the Bootstrapper as it appears that the manifest is being read from the wrong directory.

**Closed** 2024-07-12 16:59 UTC
Labels: kind/bug
