### ISSUE TITLE
[WASM] Error Using Icon from Manifest

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.resizetizer#304] opened 2024-07-12 01:56 UTC
### Current behavior

When creating a project (using either the blank or recommended preset for example) and running the application on WASM, an error appears in the logs indicating a failure to use an icon from the manifest. 

The error message is as follows:
`Error while trying to use the following icon from the Manifest: http://localhost:5000/package_d1d4b7a54fada6857b2cc5e67bbfbb6a09fb48a7/Platforms/WebAssembly/icon-512.png (Download error or resource isn't a valid image)`

### Expected behavior

The application should load without any errors in the logs.

### How to reproduce it (as minimally and precisely as possible)

1. Create a new project using either the blank or recommended preset.
2. Launch the application on the WebAssembly (WASM) platform.
3. Observe the output logs for the error message related to the manifest icon.

Sample apps used for the tests created with cli: 
- [BlankAppTest.zip](https://github.com/user-attachments/files/16186188/BlankAppTest.zip)
- [RecommendedAppTest.zip](https://github.com/user-attachments/files/16186185/RecommendedAppTest.zip)

### Workaround

N/A

### Affected Platforms

- [X] WASM

### Works on UWP/WinUI

None

### Version(s)

- Uno.Templates: 5.3.24
- Uno.Sdk: 5.3.24

### IDE

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.10.4

### Relevant plugins

N/A

**Comment by agneszitte** [comment] 2024-07-12 01:58
@jeromelaban, @dansiegel not sure if it is the correct repo for this issue. You can move it as needed.

**Comment by jeromelaban** [comment] 2024-07-12 02:00
Duplicate of https://github.com/unoplatform/uno.resizetizer/issues/303, related to https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/872

**Closed by jeromelaban** 2024-07-12 02:00 UTC
Labels: kind/bug, triage/untriaged
